const digits = (value) => value.replace(/\D/g, '');
const cpfMask = (value) => digits(value).slice(0, 11).replace(/^(\d{3})(\d)/, '$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/, '$1.$2.$3').replace(/^(\d{3})\.(\d{3})\.(\d{3})(\d)/, '$1.$2.$3-$4');
const phoneMask = (value) => { const d = digits(value).slice(0, 11); return d.length > 10 ? d.replace(/^(\d{2})(\d)/, '($1) $2').replace(/^(\(\d{2}\) \d{5})(\d)/, '$1-$2') : d.replace(/^(\d{2})(\d)/, '($1) $2').replace(/^(\(\d{2}\) \d{4})(\d)/, '$1-$2'); };
const moneyMask = (value) => { const d = digits(value); if (!d) return ''; return `R$ ${(Number(d) / 100).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; };
const moneyValue = (value) => (Number(digits(value)) / 100).toFixed(2);
const validCpf = (value) => { const cpf = digits(value); if (cpf.length !== 11 || /^(\d)\1{10}$/.test(cpf)) return false; const check = (part) => { let sum = 0, weight = part.length + 1; for (const n of part) sum += Number(n) * weight--; const rest = sum % 11; return rest < 2 ? 0 : 11 - rest; }; return Number(cpf[9]) === check(cpf.slice(0, 9)) && Number(cpf[10]) === check(cpf.slice(0, 10)); };
const showError = (field, message = '') => { const el = document.querySelector(`[data-error="${field}"]`); if (el) el.textContent = message; };
const request = async (url, options = {}) => { const response = await fetch(url, { headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, ...options }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw { status: response.status, body }; return body; };

function initList() { const table = document.getElementById('customers-table'); if (!table) return; const prev = document.getElementById('previous-page'); const next = document.getElementById('next-page'); const money = (v) => Number(v).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); const load = async (url) => { try { const data = await request(url); table.innerHTML = data.data.length ? data.data.map((c) => `<tr><td class="px-5 py-4"><strong class="block text-white">${c.nome}</strong><small class="text-slate-500">${c.email}</small></td><td class="px-5 py-4">${c.cpf}</td><td class="px-5 py-4">${c.telefone || 'Não informado'}</td><td class="px-5 py-4">${money(c.renda_mensal)}</td><td class="px-5 py-4 text-right"><a class="mr-3 text-emerald-400" href="/clientes/${c.code}/edit">Editar</a><button class="text-red-400 hover:text-red-300" data-delete="${c.code}">Excluir</button></td></tr>`).join('') : '<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Nenhum cliente cadastrado.</td></tr>'; document.getElementById('list-summary').textContent = `${data.data.length} cliente(s) nesta página`; document.getElementById('page-label').textContent = `Página ${data.meta?.current_page || 1}`; prev.disabled = !data.links?.prev; next.disabled = !data.links?.next; prev.dataset.url = data.links?.prev || ''; next.dataset.url = data.links?.next || ''; table.querySelectorAll('[data-delete]').forEach((button) => { button.onclick = async () => { if (!window.confirm('Deseja excluir este cliente?')) return; button.disabled = true; try { await request(`/api/clientes/${button.dataset.delete}`, { method: 'DELETE' }); await load(url); } catch { window.alert('Não foi possível excluir o cliente.'); button.disabled = false; } }; }); } catch { table.innerHTML = '<tr><td colspan="5" class="px-5 py-12 text-center text-red-400">Não foi possível carregar os clientes.</td></tr>'; } }; prev.onclick = () => load(prev.dataset.url); next.onclick = () => load(next.dataset.url); load('/api/clientes'); }

function initForm() { const form = document.getElementById('customer-form'); if (!form) return; const cpf = document.getElementById('cpf'); const phone = document.getElementById('telefone'); const money = document.getElementById('renda_mensal'); cpf.oninput = () => { cpf.value = cpfMask(cpf.value); }; phone.oninput = () => { phone.value = phoneMask(phone.value); }; money.oninput = () => { money.value = moneyMask(money.value); }; cpf.value = cpfMask(cpf.value); phone.value = phoneMask(phone.value); money.value = moneyMask(money.value); form.onsubmit = async (event) => { event.preventDefault(); ['nome', 'cpf', 'email', 'renda_mensal'].forEach((f) => showError(f)); const data = Object.fromEntries(new FormData(form)); data.cpf = digits(data.cpf); data.telefone = digits(data.telefone); data.renda_mensal = moneyValue(data.renda_mensal); const errors = {}; if (!data.nome.trim()) errors.nome = 'Informe o nome completo.'; if (!validCpf(data.cpf)) errors.cpf = 'Informe um CPF válido.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) errors.email = 'Informe um e-mail válido.'; if (!data.renda_mensal || Number(data.renda_mensal) <= 0) errors.renda_mensal = 'Informe uma renda maior que zero.'; Object.entries(errors).forEach(([f, m]) => showError(f, m)); if (Object.keys(errors).length) return; const button = document.getElementById('submit-button'); button.disabled = true; try { const edit = window.customerPage.mode === 'edit'; await request(edit ? `/api/clientes/${window.customerPage.code}` : '/api/clientes', { method: edit ? 'PUT' : 'POST', body: JSON.stringify(data) }); window.location.href = '/clientes'; } catch (error) { Object.entries(error.body?.errors || {}).forEach(([f, messages]) => showError(f, messages[0])); const alert = document.getElementById('form-alert'); alert.textContent = error.status === 422 ? 'Revise os campos destacados.' : 'Não foi possível salvar o cliente.'; alert.className = 'mb-6 rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300'; } finally { button.disabled = false; } }; }
document.addEventListener('DOMContentLoaded', () => { initList(); initForm(); });
